name = "ui-handler"
version = "0.1.0"
package = "/home/colin/work/agentry-workspaces/inbox-ui-dev/ui-handler/target/wasm32-unknown-unknown/release/ui_handler.composite.wasm"
static_package = false

[[handler]]
type = "runtime"

[[handler]]
type = "tcp"

[handler.client_tls]
enabled = true
skip_verify = false
auto_handshake = true

[[handler]]
type = "rpc"

[[handler]]
type = "store"
base_path = "/tmp/inbox-ui-dev-store"
store_id = "inbox"
